version: 2
jobs:
  test:
    docker:
      - image: 8.4.0-alpine
    steps:
      - checkout
      - run:
          name: Test
          command: npm test
      - store_artifacts:
          path: coverage
          prefix: coverage

workflows:
  version: 2
  build_and_test:
    jobs:
      - test
